spring:
  servlet:
    multipart:
      max-file-size: 10MB
  thymeleaf:
    cache: false
    encoding: UTF-8

netty:
  server:
    port: 8081
  websocket:
    port: 8081
    ip: 127.0.0.1
    path: /channel
    max-frame-size: 10240